"""CT-2 (BLOCKING) + B14 → the DSL-hooks delivery contract at the poll boundary.

CLOSURE TEST CT-2: "A polled DSL-hooks job surfaces a bucket URL, or terminal
delivery_unavailable."

- SOURCE (seed only): the submit body + a FakeControlPlane scripted with the
  GOLDEN CP body generated by CT-1 (tests/web/fixtures/dsl_hooks_execution_result
  .snapshot.json) — not an invented payload.
- TRIGGER: _handle_submit (outermost entrypoint) via create_app(...).test_client().
- DRIVER (async CP edge): the real _handle_poll. No sleeps.
- OBSERVE: the production poll response body + the reconciled repo row.
- FORBIDDEN SPAN: build_submission, _resolve_cp_input, insert_or_get_queued,
  dispatch_async, attach_execution_id, _resolve_result_ref, the delivery policy.
- EXECUTION: pure fakes, no infra.

Status vs code (D5): delivery_unavailable is an ERROR CODE. The DB status stays
`failed` — the terminal status set is hardcoded in SQL (pg.update_from_execution),
so a new status would need a root-owned schema change.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path

import pytest
import server
from conftest import ORG_ID, FakeControlPlane, FakeIdentity, FakeReelJobRepo, make_ctx, make_deps
from reel_jobs import (
    A1_DELIVERY_UNAVAILABLE,
    ALLOWLISTED_TARGETS,
    DELIVERY_REQUIRED_TARGETS,
    TARGET_COMPOSITE,
    TARGET_DSL_HOOKS,
    ReelJobRef,
)

GOLDEN = Path(__file__).resolve().parent / "fixtures" / "dsl_hooks_execution_result.snapshot.json"

EXEC_ID = "exec_dsl_1"
BUCKET_URL = "https://bucket.example.com/outputs/GOLDEN/reel.mp4"
NODE_PATH = "/tmp/node/out.mp4"


def _client(deps):
    return server.create_app(deps, enable_supertokens=False).test_client()


def _owned_job(ctx, target: str) -> ReelJobRef:
    """An owned, in-flight job. `target` rides in params — ReelJobRef has no
    target column, and _canonical_params always stamps params["target"]."""
    return ReelJobRef(
        job_id=uuid.uuid4(),
        org_id=ORG_ID,
        created_by=ctx.user_id,
        status="producing",
        execution_id=EXEC_ID,
        params={"target": target},
    )


def _poll(cp, *, target=TARGET_DSL_HOOKS):
    ctx = make_ctx("admin")
    job = _owned_job(ctx, target)
    repo = FakeReelJobRepo(job=job)
    deps = make_deps(identity=FakeIdentity(ctx), reel_jobs=repo, control_plane=cp)
    resp = _client(deps).get(f"/api/v1/executions/{EXEC_ID}")
    return resp, repo, job


def _cp(result: dict, status="succeeded", http_status=200):
    body = {"status": status, "result": result}
    return FakeControlPlane(response=(http_status, body, {}))


# ── CT-2 happy path: the golden CP body from CT-1 ──────────────────


def test_dsl_hooks_poll_succeeds_with_golden_ct1_body():
    """The payload replayed here is generated from CT-1's REAL worker output."""
    golden = json.loads(GOLDEN.read_text(encoding="utf-8"))

    resp, repo, _ = _poll(_cp(golden["result"], status=golden["status"]))

    assert resp.status_code == 200
    body = resp.get_json()
    assert body["status"] == "succeeded"
    assert repo.updates[-1][2] == golden["result"]["download_url"]


def test_dsl_hooks_poll_succeeds_with_browser_deliverable_url():
    resp, repo, _ = _poll(_cp({"download_url": BUCKET_URL}))

    body = resp.get_json()
    assert body["status"] == "succeeded"
    assert repo.updates[-1][2] == BUCKET_URL


# ── B14: terminal delivery_unavailable ─────────────────────────────


def test_poll_without_download_url_is_terminal_delivery_unavailable():
    resp, repo, _ = _poll(_cp({"video_path": NODE_PATH}))

    body = resp.get_json()
    assert body["status"] == "failed"                      # status, not a new enum
    assert body["error"] == A1_DELIVERY_UNAVAILABLE
    assert repo.updates[-1][1] == "failed"


def test_delivery_unavailable_never_exposes_the_node_local_path():
    resp, _, _ = _poll(_cp({"video_path": NODE_PATH}))

    assert NODE_PATH not in json.dumps(resp.get_json())


def test_delivery_unavailable_strips_the_whole_result_dict():
    """_poll_response_body does `payload = dict(cp_body)` — it leaks `result` wholesale."""
    resp, _, _ = _poll(_cp({"video_path": NODE_PATH, "reels": ["/tmp/node/a.mp4"]}))

    body = resp.get_json()
    assert "result" not in body       # the ENTIRE dict, not just result_ref
    assert "/tmp/node/a.mp4" not in json.dumps(body)


@pytest.mark.parametrize(
    "bad", [NODE_PATH, "file:///tmp/x.mp4", "https://", "s3://bucket/key", "not-a-url", ""]
)
def test_non_browser_deliverable_download_url_is_refused(bad):
    """Proves the missing scheme check: download_url/url pass verbatim today."""
    resp, repo, _ = _poll(_cp({"download_url": bad}))

    body = resp.get_json()
    assert body["status"] == "failed"
    assert body["error"] == A1_DELIVERY_UNAVAILABLE
    assert repo.updates[-1][2] is None


def test_non_browser_deliverable_url_key_is_refused():
    resp, _, _ = _poll(_cp({"url": NODE_PATH}))

    assert resp.get_json()["error"] == A1_DELIVERY_UNAVAILABLE


def test_worker_reported_error_is_preserved_not_masked():
    """A CP-reported failure keeps its own error — the delivery policy is additive."""
    cp = FakeControlPlane(response=(200, {"status": "failed", "error": "dsl_compile_failed"}, {}))
    resp, _, _ = _poll(cp)

    body = resp.get_json()
    assert body["status"] == "failed"
    assert body["error"] == "dsl_compile_failed"


# ── PARITY: all non-DSL-hooks targets keep today's fail-soft behavior ──


@pytest.mark.parametrize("target", sorted(ALLOWLISTED_TARGETS - DELIVERY_REQUIRED_TARGETS))
def test_existing_targets_keep_fail_soft_behavior(target):
    """D5 scoping: composite/topic/research must be untouched by the new policy."""
    resp, repo, _ = _poll(_cp({"video_path": NODE_PATH}), target=target)

    body = resp.get_json()
    assert body["status"] == "succeeded"                       # unchanged
    assert repo.updates[-1][2].startswith("cp-execution://")


@pytest.mark.parametrize("target", sorted(ALLOWLISTED_TARGETS - DELIVERY_REQUIRED_TARGETS))
def test_existing_targets_still_expose_their_result_dict(target):
    resp, _, _ = _poll(_cp({"video_path": NODE_PATH}), target=target)

    assert "result" in resp.get_json()


def test_delivery_required_targets_is_scoped_to_dsl_hooks():
    assert DELIVERY_REQUIRED_TARGETS == frozenset({TARGET_DSL_HOOKS})
    assert TARGET_COMPOSITE not in DELIVERY_REQUIRED_TARGETS


# ── transient CP failures stay non-terminal (existing contract) ────


def test_transient_cp_error_does_not_write_terminal_state():
    cp = _cp({}, http_status=503)
    resp, repo, _ = _poll(cp)

    assert resp.status_code == 503
    assert repo.updates == []
