"""CT-1 (BLOCKING) + B5 + B16 + B17 — the DSL-hooks worker span.

CLOSURE TEST CT-1: "A dispatched DSL-hooks job produces a downloadable reel, or
fails terminal delivery_unavailable."

- SOURCE (seed only): a1_composite.ts.md, source.words.json, a1_hook_plan.json,
  and a synthetic lavfi mp4.
- TRIGGER: dsl_hooks_to_reels (the reasoner) — the highest new connector.
- FORBIDDEN SPAN (never called/seeded/mocked here): parse_marker, resolve_text,
  align, compile_composite, validate_renderable, map_cut_ins, download_segments,
  stitch_footage_reel, finish_reel.
- OBSERVE: the reasoner's returned result dict.
- Injected seams only: ``fetch_segment`` (NEW this slice — a production param with
  a production default, mirroring ``uploader``) and ``uploader`` (pre-existing,
  app.py). Neither bypasses the span.
- EXECUTION: needs real ffmpeg. Uses fail-closed _require_ffmpeg() — NEVER skipif.
  A skipped closure test is UNVERIFIED, not green.

NOTE ON B5 vs the FORBIDDEN SPAN: test_compile_error_never_reaches_stitch_or_finish
monkeypatches stitch_footage_reel/finish_reel, which are in CT-1's forbidden span.
This is intentional and NOT a violation: B5's assertion is `calls == []`, a
NEGATIVE assertion that requires patching to observe non-invocation. It is a
different test from CT-1. Do not "fix" this.
"""

from __future__ import annotations

import asyncio
import json
import shutil
from pathlib import Path
from urllib.parse import urlparse

import pytest

from reel_af import app as app_mod
from reel_af import storage as storage_mod
from reel_af.app import dsl_hooks_to_reels
from reel_af.dsl.models import A1_DELIVERY_UNAVAILABLE

FFMPEG = shutil.which("ffmpeg")
FFPROBE = shutil.which("ffprobe")

FIXTURES = Path(__file__).resolve().parent / "dsl" / "fixtures"
A1_SOURCE_URL = "https://www.youtube.com/watch?v=abc123"
GOLDEN = Path(__file__).resolve().parent / "web" / "fixtures" / "dsl_hooks_execution_result.snapshot.json"


def _require_ffmpeg() -> None:
    """Fail-closed: a BLOCKING closure test must never skip to green."""
    if not FFMPEG or not FFPROBE:
        pytest.fail("CT-1 closure requires ffmpeg + ffprobe on PATH (fail-closed)")


@pytest.fixture
def a1_refs() -> dict:
    return {
        "source_url": A1_SOURCE_URL,
        "composite_ref": str(FIXTURES / "a1_composite.ts.md"),
        "words_ref": str(FIXTURES / "source.words.json"),
        "hook_ref": str(FIXTURES / "a1_hook_plan.json"),
        "clip_idx": 1,
    }


@pytest.fixture
def lavfi_source(tmp_path) -> Path:
    """A real synthetic source mp4 — stands in for the downloaded YouTube segment."""
    _require_ffmpeg()
    out = tmp_path / "source.mp4"
    import subprocess

    subprocess.run(
        [FFMPEG, "-y", "-f", "lavfi", "-i", "testsrc2=size=1920x1080:rate=30",
         "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000",
         "-t", "90", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
         "-shortest", str(out)],
        capture_output=True, text=True, timeout=120, check=True,
    )
    return out


def _fetch(source: Path):
    return lambda req: source


class _FakeTextProvider:
    """Stands in for the LLM (hook text). The render mechanics stay REAL.

    Matches the precedent set by tests/test_finish_closure.py: "Only whisper, the
    LLM and image generation are faked — the render mechanics are all real." The
    LLM is an external service at the edge of the span, not a step of it —
    finish_reel itself really runs and really burns pixels.
    """

    def ai(self, system=None, user=None, schema=None, **kw):
        if schema is not None:
            return {"hook": "THEY DON'T REASON", "moments": []}
        return "THEY DON'T REASON"


class _FakeImageProvider:
    """Stands in for image GENERATION only — returns a real PNG.

    Same boundary as the LLM: image generation is an external service at the edge
    of the span. The generated bytes are real, so the ffmpeg overlay burn that
    consumes them is real too.

    NOTE: passing image_provider=None would NOT disable images — it means "use the
    production default", and OpenRouterProvider constructs fine without a key and
    only fails lazily at generate_image. An explicit fake is required.
    """

    async def generate_image(self, *, prompt=None, model=None, n=1, **kw):
        import base64
        import io

        from PIL import Image

        buf = io.BytesIO()
        Image.new("RGB", (1024, 1024), (200, 30, 30)).save(buf, format="PNG")
        b64 = base64.b64encode(buf.getvalue()).decode()

        class _Img:
            b64_json = b64
            url = None

        class _Resp:
            images = [_Img()]

        return _Resp()


def _uploader_ok(local_path, *, run_id, filename=None, **kw):
    return f"https://bucket.example.com/outputs/{run_id}/{filename or 'reel.mp4'}"


def _uploader_fixed(local_path, *, run_id, filename=None, **kw):
    """Deterministic delivery URL for the golden-parity test.

    The real uploader embeds run_id (which is random per run), so a live URL
    cannot be pinned in a fixture. _normalize must NOT strip download_url — it is
    the contract field B17 exists to pin — so the URL is made stable here instead.
    """
    return "https://bucket.example.com/outputs/GOLDEN/reel.mp4"


def _uploader_none(local_path, *, run_id, filename=None, **kw):
    """The real fail-soft behavior of storage.upload_reel when the bucket is unset."""
    return None


class _DefaultUploaderFakeS3:
    def __init__(self):
        self.uploaded: list[tuple[str, str, str]] = []

    def upload_file(self, filename, bucket, key):
        self.uploaded.append((filename, bucket, key))

    def generate_presigned_url(self, operation, Params, ExpiresIn):  # noqa: N803
        assert operation == "get_object"
        return f"https://s3.example/{Params['Bucket']}/{Params['Key']}?ttl={ExpiresIn}"


def _patch_fast_render(monkeypatch, tmp_path):
    def fake_download_segments(plan, out_dir, fetch_segment):
        Path(out_dir).mkdir(parents=True, exist_ok=True)
        return []

    async def fake_stitch_footage_reel(plan, assets, out_dir, *, run_id):
        path = Path(out_dir) / "base.mp4"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"base-video")
        return path

    async def fake_finish_reel(base, ctx, cfg, *, out_dir, raw):
        path = Path(out_dir) / "final.mp4"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"final-video")
        return path

    async def fake_apply_overlays(reel, segment_assets, overlay_plan, out_dir,
                                  run_id, *, image_provider, concurrency=None):
        # B1: the overlay draw stage is part of the faked render span — the
        # real one would reject the empty fake asset map.
        return segment_assets

    monkeypatch.setattr(app_mod, "download_segments", fake_download_segments)
    monkeypatch.setattr(app_mod, "apply_overlays", fake_apply_overlays)
    monkeypatch.setattr(app_mod, "stitch_footage_reel", fake_stitch_footage_reel)
    monkeypatch.setattr(app_mod, "finish_reel", fake_finish_reel)


def _normalize(result: dict) -> dict:
    """Strip only non-deterministic fields. NEVER strips download_url/error — those
    are the contract B17 pins."""
    out = dict(result)
    for key in ("run_id", "timings_s", "video_path", "reels"):
        out.pop(key, None)
    return out


# ── B16 / CT-1: the worker contract ────────────────────────────────


def test_worker_delivers_browser_url(a1_refs, lavfi_source, tmp_path):
    _require_ffmpeg()

    result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=_fetch(lavfi_source),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
            uploader=_uploader_ok,
        )
    )

    assert "error" not in result, result
    assert result["download_url"].startswith("https://")
    assert result["target_workflow"] == "dsl_hooks"
    assert result["clip_idx"] == 1
    assert result["segment_count"] >= 1


def test_worker_without_bucket_is_terminal_delivery_unavailable(a1_refs, lavfi_source, tmp_path):
    """RED-AT-SEAM: upload_reel -> None is a reachable production state
    (storage.py returns None when REEL_BUCKET_NAME is unset)."""
    _require_ffmpeg()

    result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=_fetch(lavfi_source),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
            uploader=_uploader_none,
        )
    )

    assert result["error"] == A1_DELIVERY_UNAVAILABLE
    assert "download_url" not in result
    # Must NOT fall back to a node-local path (cf. app.py research_to_reel's
    # `download_url or video_path` anti-pattern).
    assert "video_path" not in result


def test_worker_default_uploader_delivers_with_configured_bucket(
    a1_refs, tmp_path, monkeypatch
):
    """The production default uploader path is storage.upload_reel, not an injected callable."""
    monkeypatch.setenv("REEL_BUCKET_NAME", "reel-uploads-test")
    s3 = _DefaultUploaderFakeS3()
    monkeypatch.setattr(storage_mod, "_client", lambda client_factory=None: s3)
    _patch_fast_render(monkeypatch, tmp_path)

    result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=lambda req: pytest.fail("download_segments is faked"),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
        )
    )

    assert "error" not in result, result
    parsed = urlparse(result["download_url"])
    assert parsed.scheme in {"http", "https"}
    assert parsed.netloc
    assert result["target_workflow"] == "dsl_hooks"
    assert len(s3.uploaded) == 1
    assert s3.uploaded[0][1] == "reel-uploads-test"
    assert s3.uploaded[0][2].startswith(f"outputs/{result['run_id']}/")


def test_worker_default_uploader_without_bucket_is_delivery_unavailable(
    a1_refs, tmp_path, monkeypatch
):
    monkeypatch.delenv("REEL_BUCKET_NAME", raising=False)
    monkeypatch.setattr(
        storage_mod,
        "_client",
        lambda client_factory=None: pytest.fail("S3 client must not be constructed"),
    )
    _patch_fast_render(monkeypatch, tmp_path)

    result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=lambda req: pytest.fail("download_segments is faked"),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
        )
    )

    assert result["error"] == A1_DELIVERY_UNAVAILABLE
    assert "download_url" not in result
    assert "video_path" not in result


def test_worker_rejects_non_http_delivery_url(a1_refs, lavfi_source, tmp_path):
    """A node-local path returned as a 'download_url' is not browser-deliverable."""
    _require_ffmpeg()

    result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=_fetch(lavfi_source),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
            uploader=lambda p, *, run_id, filename=None, **kw: "/tmp/node/out.mp4",
        )
    )

    assert result["error"] == A1_DELIVERY_UNAVAILABLE
    assert "/tmp/node/out.mp4" not in json.dumps(result)


def test_worker_maps_cutins_from_hook_plan(a1_refs, lavfi_source, tmp_path):
    """B9a wiring: A1 zoom/visual cut-ins are validated by the worker.

    Slice A MAPS cut-ins; it does not render them (B9b deferred).
    """
    _require_ffmpeg()

    result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=_fetch(lavfi_source),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
            uploader=_uploader_ok,
        )
    )

    assert result["cut_in_count"] == 2


def test_worker_fails_closed_on_unmappable_cutin(a1_refs, lavfi_source, tmp_path):
    _require_ffmpeg()
    bad_hook = tmp_path / "bad_hook.json"
    plan = json.loads(Path(a1_refs["hook_ref"]).read_text())
    plan["clips"][0]["cut_ins"] = [
        {"type": "zoom", "at_s": 9000.0, "until_s": 9001.0, "line": "nowhere"}
    ]
    bad_hook.write_text(json.dumps(plan))

    result = asyncio.run(
        dsl_hooks_to_reels(
            **{**a1_refs, "hook_ref": str(bad_hook)},
            out_dir=str(tmp_path / "work"),
            fetch_segment=_fetch(lavfi_source),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
            uploader=_uploader_ok,
        )
    )

    assert result["error"] == "dsl_cutin_invalid"
    assert "CUTIN_INVALID" in {d["code"] for d in result["diagnostics"]}


def test_worker_missing_artifact_fails_closed_before_render(a1_refs, tmp_path):
    result = asyncio.run(
        dsl_hooks_to_reels(
            **{**a1_refs, "composite_ref": str(tmp_path / "nope.ts.md")},
            out_dir=str(tmp_path / "work"),
            fetch_segment=lambda req: pytest.fail("must not fetch"),
            uploader=lambda *a, **k: pytest.fail("must not upload"),
        )
    )

    assert result["error"] == "dsl_artifact_unavailable"


def test_worker_remote_artifact_fetch_failure_fails_closed(a1_refs, tmp_path):
    """reel-af on Railway pulls A1 artifacts over http(s); a failed fetch is
    terminal dsl_artifact_unavailable, not a crash — before any render side effect."""
    remote = {
        **a1_refs,
        "composite_ref": "https://a1.example/runs/x/composite.ts.md",
        "words_ref": "https://a1.example/runs/x/words.json",
        "hook_ref": "https://a1.example/runs/x/hook-plan.json",
    }
    result = asyncio.run(
        dsl_hooks_to_reels(
            **remote,
            out_dir=str(tmp_path / "work"),
            artifact_fetch=lambda url: (_ for _ in ()).throw(OSError("502 from A1")),
            fetch_segment=lambda req: pytest.fail("must not fetch segment"),
            uploader=lambda *a, **k: pytest.fail("must not upload"),
        )
    )

    assert result["error"] == "dsl_artifact_unavailable"
    assert "502 from A1" in result["detail"]


def test_worker_expired_presigned_artifact_fetch_fails_as_artifact_unavailable(a1_refs, tmp_path):
    remote = {
        **a1_refs,
        "composite_ref": "https://s3.example/reel-uploads/plans/x/composite.ts.md?expired=1",
        "words_ref": "https://s3.example/reel-uploads/plans/x/transcript.words.json?expired=1",
        "hook_ref": "https://s3.example/reel-uploads/plans/x/hook-plan.json?expired=1",
    }

    result = asyncio.run(
        dsl_hooks_to_reels(
            **remote,
            out_dir=str(tmp_path / "work"),
            artifact_fetch=lambda url: (_ for _ in ()).throw(OSError("403 expired presign")),
            fetch_segment=lambda req: pytest.fail("must not fetch segment"),
            uploader=lambda *a, **k: pytest.fail("must not upload"),
        )
    )

    assert result["error"] == "dsl_artifact_unavailable"
    assert "403 expired presign" in result["detail"]


def test_worker_rejects_non_http_source_url(a1_refs, tmp_path):
    result = asyncio.run(
        dsl_hooks_to_reels(
            **{**a1_refs, "source_url": "/etc/passwd"},
            out_dir=str(tmp_path / "work"),
            fetch_segment=lambda req: pytest.fail("must not fetch"),
            uploader=lambda *a, **k: pytest.fail("must not upload"),
        )
    )

    assert result["error"] == "invalid_source_url"


# ── B5: compile errors never reach stitch/finish ───────────────────


def test_compile_error_never_reaches_stitch_or_finish(a1_refs, tmp_path, monkeypatch):
    """B5. See the module docstring note on monkeypatching CT-1's span."""
    calls: list[str] = []
    monkeypatch.setattr(app_mod, "stitch_footage_reel",
                        lambda *a, **k: calls.append("stitch"))
    monkeypatch.setattr(app_mod, "finish_reel", lambda *a, **k: calls.append("finish"))

    bogus = tmp_path / "bogus.ts.md"
    bogus.write_text("00:00:04.120  this text appears nowhere in the source transcript\n")

    result = asyncio.run(
        dsl_hooks_to_reels(
            **{**a1_refs, "composite_ref": str(bogus)},
            out_dir=str(tmp_path / "work"),
            fetch_segment=lambda req: pytest.fail("must not fetch"),
            uploader=lambda *a, **k: pytest.fail("must not upload"),
        )
    )

    assert result["error"] == "dsl_compile_failed"
    assert result["diagnostics"]
    assert calls == []  # the load-bearing assertion


def test_invalid_marker_never_reaches_stitch_or_finish(a1_refs, tmp_path, monkeypatch):
    calls: list[str] = []
    monkeypatch.setattr(app_mod, "stitch_footage_reel", lambda *a, **k: calls.append("stitch"))
    monkeypatch.setattr(app_mod, "finish_reel", lambda *a, **k: calls.append("finish"))

    bad = tmp_path / "bad_marker.ts.md"
    bad.write_text(
        "00:00:04.120  They don't reason. They pattern-match at a scale that"
        " feels like reasoning.\n\n[bogus 1.0]\n"
    )

    result = asyncio.run(
        dsl_hooks_to_reels(
            **{**a1_refs, "composite_ref": str(bad)},
            out_dir=str(tmp_path / "work"),
            fetch_segment=lambda req: pytest.fail("must not fetch"),
            uploader=lambda *a, **k: pytest.fail("must not upload"),
        )
    )

    assert result["error"] == "dsl_compile_failed"
    assert "INVALID_MARKER" in {d["code"] for d in result["diagnostics"]}
    assert calls == []


# ── B17 (BLOCKING): CT-1 <-> CT-2 golden parity ────────────────────


def test_ct2_golden_fixture_matches_real_worker_output(a1_refs, lavfi_source, tmp_path, request):
    """PARITY: the CP body CT-2 replays must equal what the worker ACTUALLY returns.

    REAL_WORKER_RESULT is a LIVE INVOCATION, never a hand-authored constant — a
    constant here would make this a tautology and silently void the CT-1/CT-2
    closure guarantee (R5).

    Regenerate (never hand-edit the fixture):
        uv run --extra dev python -m pytest \\
          tests/test_dsl_hooks_worker_closure.py --regenerate-golden -q
    """
    _require_ffmpeg()

    real_worker_result = asyncio.run(
        dsl_hooks_to_reels(
            **a1_refs,
            out_dir=str(tmp_path / "work"),
            fetch_segment=_fetch(lavfi_source),
            text_provider=_FakeTextProvider(),
            image_provider=_FakeImageProvider(),
            uploader=_uploader_fixed,
        )
    )

    if request.config.getoption("--regenerate-golden"):
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(
            json.dumps(
                {"status": "succeeded", "result": _normalize(real_worker_result)},
                indent=2, sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )

    assert GOLDEN.exists(), (
        f"golden fixture missing: {GOLDEN}. Regenerate with --regenerate-golden"
    )
    golden = json.loads(GOLDEN.read_text(encoding="utf-8"))

    assert golden["result"] == _normalize(real_worker_result)
    # The contract fields must survive normalization.
    assert "download_url" in golden["result"]
    assert golden["status"] == "succeeded"
