"""Composite Transcript DSL v2 package."""

from reel_af.dsl.models import (
    AlignedSpan,
    AlignResult,
    BlackSegment,
    CompileResult,
    Diagnostic,
    DiagnosticCode,
    DownloadedSegment,
    DslWord,
    FallbackSegment,
    FootageReel,
    HoleChoice,
    HoleContext,
    HoleDomain,
    RenderabilityError,
    ResolveResult,
    Segment,
    SegmentAssetMap,
    SegmentFetchRequest,
    SourceRef,
    SourceSegment,
    Transition,
    UnmatchedSpan,
    WordsSidecar,
    validate_renderable,
)

__all__ = [
    "AlignedSpan",
    "AlignResult",
    "BlackSegment",
    "CompileResult",
    "Diagnostic",
    "DiagnosticCode",
    "DownloadedSegment",
    "DslWord",
    "FallbackSegment",
    "FootageReel",
    "HoleChoice",
    "HoleContext",
    "HoleDomain",
    "RenderabilityError",
    "ResolveResult",
    "Segment",
    "SegmentAssetMap",
    "SegmentFetchRequest",
    "SourceRef",
    "SourceSegment",
    "Transition",
    "UnmatchedSpan",
    "WordsSidecar",
    "validate_renderable",
]
