# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArrangeReel(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ReelBlueprint:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ArrangeReel", llm_response=llm_response, mode="request")
        return typing.cast(types.ReelBlueprint, __result__)

    def CheckScriptCoherence(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ScriptCoherenceReport:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckScriptCoherence", llm_response=llm_response, mode="request")
        return typing.cast(types.ScriptCoherenceReport, __result__)

    def MineCandidates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.CandidateSpan"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MineCandidates", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.CandidateSpan"], __result__)

    def StrategizeReel(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ReelStrategy:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="StrategizeReel", llm_response=llm_response, mode="request")
        return typing.cast(types.ReelStrategy, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArrangeReel(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ReelBlueprint:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ArrangeReel", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ReelBlueprint, __result__)

    def CheckScriptCoherence(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ScriptCoherenceReport:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckScriptCoherence", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ScriptCoherenceReport, __result__)

    def MineCandidates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.CandidateSpan"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MineCandidates", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.CandidateSpan"], __result__)

    def StrategizeReel(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ReelStrategy:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="StrategizeReel", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ReelStrategy, __result__)

    