# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (12)
# #########################################################################

class Beat(BaseModel):
    role: typing.Optional[types.BeatRole] = None
    span_quote: typing.Optional[str] = None
    candidate_id: typing.Optional[str] = None
    occurrence_index: typing.Optional[int] = None
    max_len_s: typing.Optional[float] = None
    cutin: typing.Optional["CutIn"] = None
    interrupt_out: typing.Optional["Interrupt"] = None
    engagement: typing.Optional["Engagement"] = None

class CandidateSpan(BaseModel):
    quote: typing.Optional[str] = None
    approx_start_s: typing.Optional[float] = None
    approx_end_s: typing.Optional[float] = None
    value_score: typing.Optional[float] = None
    emotion: typing.Optional[str] = None
    is_claim: typing.Optional[bool] = None
    payoff_worthy: typing.Optional[bool] = None
    rationale: typing.Optional[str] = None

class CtaPlan(BaseModel):
    hardness: typing.Optional[types.CtaHardness] = None
    placements: typing.Optional[typing.List[str]] = None

class CutIn(BaseModel):
    type: typing.Optional[types.CutInKind] = None
    offset_s: typing.Optional[float] = None
    dur_s: typing.Optional[float] = None
    line: typing.Optional[str] = None
    image_prompt: typing.Optional[str] = None
    zoom_focus: typing.Optional[str] = None

class DurationBounds(BaseModel):
    min_s: typing.Optional[float] = None
    max_s: typing.Optional[float] = None

class Engagement(BaseModel):
    kind: typing.Optional[types.EngagementKind] = None
    line: typing.Optional[str] = None
    primary: typing.Optional[bool] = None

class Hook(BaseModel):
    type: typing.Optional[types.HookType] = None
    banner_line: typing.Optional[str] = None
    span_quote: typing.Optional[str] = None
    candidate_id: typing.Optional[str] = None
    occurrence_index: typing.Optional[int] = None

class Interrupt(BaseModel):
    kind: typing.Optional[types.InterruptKind] = None
    effect: typing.Optional[types.XfadeEffect] = None
    dur_s: typing.Optional[float] = None

class LoopPlan(BaseModel):
    strategy: typing.Optional[str] = None
    final_span_quote: typing.Optional[str] = None
    candidate_id: typing.Optional[str] = None
    occurrence_index: typing.Optional[int] = None

class PlannerCandidate(BaseModel):
    candidate_id: typing.Optional[str] = None
    quote: typing.Optional[str] = None
    occurrence_index: typing.Optional[int] = None
    word_range: typing.List[int]
    start_s: typing.Optional[float] = None
    end_s: typing.Optional[float] = None
    quality: typing.Optional[float] = None
    value_score: typing.Optional[float] = None
    emotion: typing.Optional[str] = None
    is_claim: typing.Optional[bool] = None
    payoff_worthy: typing.Optional[bool] = None
    rationale: typing.Optional[str] = None

class ReelBlueprint(BaseModel):
    template_: typing.Optional[types.Template] = None
    target_duration_s: typing.Optional[float] = None
    hook: typing.Optional["Hook"] = None
    beats: typing.List["Beat"]
    loop: typing.Optional["LoopPlan"] = None
    engagement_primary: typing.Optional[types.EngagementKind] = None
    cta: typing.Optional["CtaPlan"] = None
    rationale: typing.Optional[str] = None

class ReelStrategy(BaseModel):
    template_: typing.Optional[types.Template] = None
    target_duration_s: typing.Optional[float] = None
    hook: typing.Optional["Hook"] = None
    engagement_primary: typing.Optional[types.EngagementKind] = None
    cta: typing.Optional["CtaPlan"] = None
    rationale: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
