# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (8)
# #########################################################################

class BeatRole(str, Enum):
    Hook = "Hook"
    Context = "Context"
    Value = "Value"
    Payoff = "Payoff"
    Cta = "Cta"

class CtaHardness(str, Enum):
    Soft = "Soft"
    Medium = "Medium"
    Hard = "Hard"
    NoCta = "NoCta"

class CutInKind(str, Enum):
    Zoom = "Zoom"
    Visual = "Visual"

class EngagementKind(str, Enum):
    Send = "Send"
    Save = "Save"
    Share = "Share"
    Comment = "Comment"
    Follow = "Follow"
    NoEngagement = "NoEngagement"

class HookType(str, Enum):
    CuriosityGap = "CuriosityGap"
    BoldClaim = "BoldClaim"
    DirectCallout = "DirectCallout"
    ResultFirst = "ResultFirst"
    Question = "Question"
    PainPoint = "PainPoint"
    Number = "Number"
    PatternInterrupt = "PatternInterrupt"

class InterruptKind(str, Enum):
    Trans = "Trans"
    Join = "Join"
    Black = "Black"

class Template(str, Enum):
    HookContextValuePayoffCta = "HookContextValuePayoffCta"
    ProblemAgitateSolve = "ProblemAgitateSolve"
    BeforeAfterBridge = "BeforeAfterBridge"
    MythBust = "MythBust"
    Listicle = "Listicle"
    Storytime = "Storytime"

class XfadeEffect(str, Enum):
    Dissolve = "Dissolve"
    Smoothleft = "Smoothleft"
    Smoothright = "Smoothright"
    Smoothup = "Smoothup"
    Smoothdown = "Smoothdown"
    Hblur = "Hblur"
    Circleopen = "Circleopen"
    Radial = "Radial"
    Pixelize = "Pixelize"
    Fadeblack = "Fadeblack"
    Fadewhite = "Fadewhite"
    Fade = "Fade"
    NoEffect = "NoEffect"

# #########################################################################
# Generated classes (12)
# #########################################################################

class Beat(BaseModel):
    role: BeatRole
    span_quote: str
    candidate_id: str
    occurrence_index: int
    max_len_s: float
    cutin: typing.Optional["CutIn"] = None
    interrupt_out: typing.Optional["Interrupt"] = None
    engagement: typing.Optional["Engagement"] = None

class CandidateSpan(BaseModel):
    quote: str
    approx_start_s: typing.Optional[float] = None
    approx_end_s: typing.Optional[float] = None
    value_score: float
    emotion: typing.Optional[str] = None
    is_claim: typing.Optional[bool] = None
    payoff_worthy: typing.Optional[bool] = None
    rationale: typing.Optional[str] = None

class CtaPlan(BaseModel):
    hardness: CtaHardness
    placements: typing.Optional[typing.List[str]] = None

class CutIn(BaseModel):
    type: CutInKind
    offset_s: float
    dur_s: float
    line: typing.Optional[str] = None
    image_prompt: typing.Optional[str] = None
    zoom_focus: typing.Optional[str] = None

class DurationBounds(BaseModel):
    min_s: float
    max_s: float

class Engagement(BaseModel):
    kind: EngagementKind
    line: typing.Optional[str] = None
    primary: typing.Optional[bool] = None

class Hook(BaseModel):
    type: HookType
    banner_line: str
    span_quote: str
    candidate_id: str
    occurrence_index: int

class Interrupt(BaseModel):
    kind: InterruptKind
    effect: typing.Optional[XfadeEffect] = None
    dur_s: typing.Optional[float] = None

class LoopPlan(BaseModel):
    strategy: str
    final_span_quote: str
    candidate_id: str
    occurrence_index: int

class PlannerCandidate(BaseModel):
    candidate_id: str
    quote: str
    occurrence_index: int
    word_range: typing.List[int]
    start_s: float
    end_s: float
    quality: float
    value_score: float
    emotion: typing.Optional[str] = None
    is_claim: typing.Optional[bool] = None
    payoff_worthy: typing.Optional[bool] = None
    rationale: typing.Optional[str] = None

class ReelBlueprint(BaseModel):
    template_: Template
    target_duration_s: float
    hook: "Hook"
    beats: typing.List["Beat"]
    loop: "LoopPlan"
    engagement_primary: EngagementKind
    cta: "CtaPlan"
    rationale: typing.Optional[str] = None

class ReelStrategy(BaseModel):
    template_: Template
    target_duration_s: float
    hook: "Hook"
    engagement_primary: EngagementKind
    cta: "CtaPlan"
    rationale: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
