# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ArcPlan": types.ArcPlan,
    "stream_types.ArcPlan": stream_types.ArcPlan,

    "types.Beat": types.Beat,
    "stream_types.Beat": stream_types.Beat,

    "types.CandidateSpan": types.CandidateSpan,
    "stream_types.CandidateSpan": stream_types.CandidateSpan,

    "types.CandidateTranscriptContext": types.CandidateTranscriptContext,
    "stream_types.CandidateTranscriptContext": stream_types.CandidateTranscriptContext,

    "types.CtaPlan": types.CtaPlan,
    "stream_types.CtaPlan": stream_types.CtaPlan,

    "types.CutIn": types.CutIn,
    "stream_types.CutIn": stream_types.CutIn,

    "types.DurationBounds": types.DurationBounds,
    "stream_types.DurationBounds": stream_types.DurationBounds,

    "types.DurationPolicy": types.DurationPolicy,
    "stream_types.DurationPolicy": stream_types.DurationPolicy,

    "types.DurationRange": types.DurationRange,
    "stream_types.DurationRange": stream_types.DurationRange,

    "types.Engagement": types.Engagement,
    "stream_types.Engagement": stream_types.Engagement,

    "types.Hook": types.Hook,
    "stream_types.Hook": stream_types.Hook,

    "types.Interrupt": types.Interrupt,
    "stream_types.Interrupt": stream_types.Interrupt,

    "types.LoopPlan": types.LoopPlan,
    "stream_types.LoopPlan": stream_types.LoopPlan,

    "types.PlannerCandidate": types.PlannerCandidate,
    "stream_types.PlannerCandidate": stream_types.PlannerCandidate,

    "types.ReelBlueprint": types.ReelBlueprint,
    "stream_types.ReelBlueprint": stream_types.ReelBlueprint,

    "types.ReelStrategy": types.ReelStrategy,
    "stream_types.ReelStrategy": stream_types.ReelStrategy,

    "types.ScriptBeatText": types.ScriptBeatText,
    "stream_types.ScriptBeatText": stream_types.ScriptBeatText,

    "types.ScriptCoherenceReport": types.ScriptCoherenceReport,
    "stream_types.ScriptCoherenceReport": stream_types.ScriptCoherenceReport,

    "types.ScriptTransition": types.ScriptTransition,
    "stream_types.ScriptTransition": stream_types.ScriptTransition,

    "types.ScriptTransitionReview": types.ScriptTransitionReview,
    "stream_types.ScriptTransitionReview": stream_types.ScriptTransitionReview,


    "types.BeatRole": types.BeatRole,

    "types.CtaHardness": types.CtaHardness,

    "types.CutInKind": types.CutInKind,

    "types.EngagementKind": types.EngagementKind,

    "types.HookType": types.HookType,

    "types.InterruptKind": types.InterruptKind,

    "types.ScriptCoherenceFixAction": types.ScriptCoherenceFixAction,

    "types.ScriptTransitionVerdict": types.ScriptTransitionVerdict,

    "types.Template": types.Template,

    "types.XfadeEffect": types.XfadeEffect,

}