# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Beat": types.Beat,
    "stream_types.Beat": stream_types.Beat,

    "types.CandidateSpan": types.CandidateSpan,
    "stream_types.CandidateSpan": stream_types.CandidateSpan,

    "types.CtaPlan": types.CtaPlan,
    "stream_types.CtaPlan": stream_types.CtaPlan,

    "types.CutIn": types.CutIn,
    "stream_types.CutIn": stream_types.CutIn,

    "types.DurationBounds": types.DurationBounds,
    "stream_types.DurationBounds": stream_types.DurationBounds,

    "types.Engagement": types.Engagement,
    "stream_types.Engagement": stream_types.Engagement,

    "types.Hook": types.Hook,
    "stream_types.Hook": stream_types.Hook,

    "types.Interrupt": types.Interrupt,
    "stream_types.Interrupt": stream_types.Interrupt,

    "types.LoopPlan": types.LoopPlan,
    "stream_types.LoopPlan": stream_types.LoopPlan,

    "types.PlannerCandidate": types.PlannerCandidate,
    "stream_types.PlannerCandidate": stream_types.PlannerCandidate,

    "types.ReelBlueprint": types.ReelBlueprint,
    "stream_types.ReelBlueprint": stream_types.ReelBlueprint,

    "types.ReelStrategy": types.ReelStrategy,
    "stream_types.ReelStrategy": stream_types.ReelStrategy,


    "types.BeatRole": types.BeatRole,

    "types.CtaHardness": types.CtaHardness,

    "types.CutInKind": types.CutInKind,

    "types.EngagementKind": types.EngagementKind,

    "types.HookType": types.HookType,

    "types.InterruptKind": types.InterruptKind,

    "types.Template": types.Template,

    "types.XfadeEffect": types.XfadeEffect,

}